/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppChatRouteRouteImport } from './routes/_app/chat/route'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppChatIdRouteImport } from './routes/_app/chat/$id'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdPlansPlanSlugRouteImport } from './routes/_app/projects/$projectId/plans/$planSlug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRouteRoute = AppChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdPlansPlanSlugRoute =
  AppProjectsProjectIdPlansPlanSlugRouteImport.update({
    id: '/projects/$projectId/plans/$planSlug',
    path: '/projects/$projectId/plans/$planSlug',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRouteRouteWithChildren
  '/chat/$id': typeof AppChatIdRoute
  '/chat/': typeof AppChatIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/chat/$id': typeof AppChatIdRoute
  '/chat': typeof AppChatIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chat': typeof AppChatRouteRouteWithChildren
  '/_app/chat/$id': typeof AppChatIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/chat'
    | '/chat/$id'
    | '/chat/'
    | '/projects/$projectId/'
    | '/projects/$projectId/plans/$planSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/chat/$id'
    | '/chat'
    | '/projects/$projectId'
    | '/projects/$projectId/plans/$planSlug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/_app/chat'
    | '/_app/chat/$id'
    | '/_app/chat/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/plans/$planSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppChatRouteRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/plans/$planSlug': {
      id: '/_app/projects/$projectId/plans/$planSlug'
      path: '/projects/$projectId/plans/$planSlug'
      fullPath: '/projects/$projectId/plans/$planSlug'
      preLoaderRoute: typeof AppProjectsProjectIdPlansPlanSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChatRouteRouteChildren {
  AppChatIdRoute: typeof AppChatIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteRouteChildren: AppChatRouteRouteChildren = {
  AppChatIdRoute: AppChatIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteRouteWithChildren = AppChatRouteRoute._addFileChildren(
  AppChatRouteRouteChildren,
)

interface AppRouteChildren {
  AppChatRouteRoute: typeof AppChatRouteRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdPlansPlanSlugRoute: typeof AppProjectsProjectIdPlansPlanSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRouteRoute: AppChatRouteRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdPlansPlanSlugRoute:
    AppProjectsProjectIdPlansPlanSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
