/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSandboxRouteImport } from './routes/_app/sandbox'
import { Route as AppSettingsSuggestionsRouteImport } from './routes/_app/settings/suggestions'
import { Route as AppSettingsProvidersRouteImport } from './routes/_app/settings/providers'
import { Route as AppSettingsGitRouteImport } from './routes/_app/settings/git'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdTasksIndexRouteImport } from './routes/_app/projects/$projectId/tasks/index'
import { Route as AppProjectsProjectIdSpacesIndexRouteImport } from './routes/_app/projects/$projectId/spaces/index'
import { Route as AppProjectsProjectIdSkillsIndexRouteImport } from './routes/_app/projects/$projectId/skills/index'
import { Route as AppProjectsProjectIdSettingsIndexRouteImport } from './routes/_app/projects/$projectId/settings/index'
import { Route as AppProjectsProjectIdPlansIndexRouteImport } from './routes/_app/projects/$projectId/plans/index'
import { Route as AppProjectsProjectIdChatsIndexRouteImport } from './routes/_app/projects/$projectId/chats/index'
import { Route as AppProjectsProjectIdPlansPlanSlugRouteImport } from './routes/_app/projects/$projectId/plans/$planSlug'
import { Route as AppProjectsProjectIdChatsChatIdRouteImport } from './routes/_app/projects/$projectId/chats/$chatId'
import { Route as AppProjectsProjectIdSpacesSpaceIdIndexRouteImport } from './routes/_app/projects/$projectId/spaces/$spaceId/index'
import { Route as AppProjectsProjectIdSpacesSpaceIdChatIdRouteImport } from './routes/_app/projects/$projectId/spaces/$spaceId/$chatId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSuggestionsRoute = AppSettingsSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProvidersRoute = AppSettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGitRoute = AppSettingsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksIndexRoute =
  AppProjectsProjectIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSpacesIndexRoute =
  AppProjectsProjectIdSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSkillsIndexRoute =
  AppProjectsProjectIdSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsIndexRoute =
  AppProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPlansIndexRoute =
  AppProjectsProjectIdPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdChatsIndexRoute =
  AppProjectsProjectIdChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPlansPlanSlugRoute =
  AppProjectsProjectIdPlansPlanSlugRouteImport.update({
    id: '/plans/$planSlug',
    path: '/plans/$planSlug',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdChatsChatIdRoute =
  AppProjectsProjectIdChatsChatIdRouteImport.update({
    id: '/chats/$chatId',
    path: '/chats/$chatId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSpacesSpaceIdIndexRoute =
  AppProjectsProjectIdSpacesSpaceIdIndexRouteImport.update({
    id: '/spaces/$spaceId/',
    path: '/spaces/$spaceId/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSpacesSpaceIdChatIdRoute =
  AppProjectsProjectIdSpacesSpaceIdChatIdRouteImport.update({
    id: '/spaces/$spaceId/$chatId',
    path: '/spaces/$spaceId/$chatId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sandbox': typeof AppSandboxRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/git': typeof AppSettingsGitRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/suggestions': typeof AppSettingsSuggestionsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/chats/$chatId': typeof AppProjectsProjectIdChatsChatIdRoute
  '/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
  '/projects/$projectId/chats/': typeof AppProjectsProjectIdChatsIndexRoute
  '/projects/$projectId/plans/': typeof AppProjectsProjectIdPlansIndexRoute
  '/projects/$projectId/settings/': typeof AppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/skills/': typeof AppProjectsProjectIdSkillsIndexRoute
  '/projects/$projectId/spaces/': typeof AppProjectsProjectIdSpacesIndexRoute
  '/projects/$projectId/tasks/': typeof AppProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/spaces/$spaceId/$chatId': typeof AppProjectsProjectIdSpacesSpaceIdChatIdRoute
  '/projects/$projectId/spaces/$spaceId/': typeof AppProjectsProjectIdSpacesSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/sandbox': typeof AppSandboxRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/': typeof AppIndexRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/git': typeof AppSettingsGitRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/suggestions': typeof AppSettingsSuggestionsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/chats/$chatId': typeof AppProjectsProjectIdChatsChatIdRoute
  '/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
  '/projects/$projectId/chats': typeof AppProjectsProjectIdChatsIndexRoute
  '/projects/$projectId/plans': typeof AppProjectsProjectIdPlansIndexRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/skills': typeof AppProjectsProjectIdSkillsIndexRoute
  '/projects/$projectId/spaces': typeof AppProjectsProjectIdSpacesIndexRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/spaces/$spaceId/$chatId': typeof AppProjectsProjectIdSpacesSpaceIdChatIdRoute
  '/projects/$projectId/spaces/$spaceId': typeof AppProjectsProjectIdSpacesSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/sandbox': typeof AppSandboxRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/git': typeof AppSettingsGitRoute
  '/_app/settings/providers': typeof AppSettingsProvidersRoute
  '/_app/settings/suggestions': typeof AppSettingsSuggestionsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/chats/$chatId': typeof AppProjectsProjectIdChatsChatIdRoute
  '/_app/projects/$projectId/plans/$planSlug': typeof AppProjectsProjectIdPlansPlanSlugRoute
  '/_app/projects/$projectId/chats/': typeof AppProjectsProjectIdChatsIndexRoute
  '/_app/projects/$projectId/plans/': typeof AppProjectsProjectIdPlansIndexRoute
  '/_app/projects/$projectId/settings/': typeof AppProjectsProjectIdSettingsIndexRoute
  '/_app/projects/$projectId/skills/': typeof AppProjectsProjectIdSkillsIndexRoute
  '/_app/projects/$projectId/spaces/': typeof AppProjectsProjectIdSpacesIndexRoute
  '/_app/projects/$projectId/tasks/': typeof AppProjectsProjectIdTasksIndexRoute
  '/_app/projects/$projectId/spaces/$spaceId/$chatId': typeof AppProjectsProjectIdSpacesSpaceIdChatIdRoute
  '/_app/projects/$projectId/spaces/$spaceId/': typeof AppProjectsProjectIdSpacesSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/login'
    | '/sandbox'
    | '/settings'
    | '/projects/$projectId'
    | '/settings/general'
    | '/settings/git'
    | '/settings/providers'
    | '/settings/suggestions'
    | '/projects/$projectId/'
    | '/projects/$projectId/chats/$chatId'
    | '/projects/$projectId/plans/$planSlug'
    | '/projects/$projectId/chats/'
    | '/projects/$projectId/plans/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/skills/'
    | '/projects/$projectId/spaces/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/spaces/$spaceId/$chatId'
    | '/projects/$projectId/spaces/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/sandbox'
    | '/settings'
    | '/'
    | '/settings/general'
    | '/settings/git'
    | '/settings/providers'
    | '/settings/suggestions'
    | '/projects/$projectId'
    | '/projects/$projectId/chats/$chatId'
    | '/projects/$projectId/plans/$planSlug'
    | '/projects/$projectId/chats'
    | '/projects/$projectId/plans'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/skills'
    | '/projects/$projectId/spaces'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/spaces/$spaceId/$chatId'
    | '/projects/$projectId/spaces/$spaceId'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/login'
    | '/_app/sandbox'
    | '/_app/settings'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/_app/settings/general'
    | '/_app/settings/git'
    | '/_app/settings/providers'
    | '/_app/settings/suggestions'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/chats/$chatId'
    | '/_app/projects/$projectId/plans/$planSlug'
    | '/_app/projects/$projectId/chats/'
    | '/_app/projects/$projectId/plans/'
    | '/_app/projects/$projectId/settings/'
    | '/_app/projects/$projectId/skills/'
    | '/_app/projects/$projectId/spaces/'
    | '/_app/projects/$projectId/tasks/'
    | '/_app/projects/$projectId/spaces/$spaceId/$chatId'
    | '/_app/projects/$projectId/spaces/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/suggestions': {
      id: '/_app/settings/suggestions'
      path: '/suggestions'
      fullPath: '/settings/suggestions'
      preLoaderRoute: typeof AppSettingsSuggestionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/providers': {
      id: '/_app/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AppSettingsProvidersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/git': {
      id: '/_app/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof AppSettingsGitRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks/': {
      id: '/_app/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks/'
      preLoaderRoute: typeof AppProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/spaces/': {
      id: '/_app/projects/$projectId/spaces/'
      path: '/spaces'
      fullPath: '/projects/$projectId/spaces/'
      preLoaderRoute: typeof AppProjectsProjectIdSpacesIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/skills/': {
      id: '/_app/projects/$projectId/skills/'
      path: '/skills'
      fullPath: '/projects/$projectId/skills/'
      preLoaderRoute: typeof AppProjectsProjectIdSkillsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings/': {
      id: '/_app/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/plans/': {
      id: '/_app/projects/$projectId/plans/'
      path: '/plans'
      fullPath: '/projects/$projectId/plans/'
      preLoaderRoute: typeof AppProjectsProjectIdPlansIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/chats/': {
      id: '/_app/projects/$projectId/chats/'
      path: '/chats'
      fullPath: '/projects/$projectId/chats/'
      preLoaderRoute: typeof AppProjectsProjectIdChatsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/plans/$planSlug': {
      id: '/_app/projects/$projectId/plans/$planSlug'
      path: '/plans/$planSlug'
      fullPath: '/projects/$projectId/plans/$planSlug'
      preLoaderRoute: typeof AppProjectsProjectIdPlansPlanSlugRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/chats/$chatId': {
      id: '/_app/projects/$projectId/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/projects/$projectId/chats/$chatId'
      preLoaderRoute: typeof AppProjectsProjectIdChatsChatIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/spaces/$spaceId/': {
      id: '/_app/projects/$projectId/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/projects/$projectId/spaces/$spaceId/'
      preLoaderRoute: typeof AppProjectsProjectIdSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/spaces/$spaceId/$chatId': {
      id: '/_app/projects/$projectId/spaces/$spaceId/$chatId'
      path: '/spaces/$spaceId/$chatId'
      fullPath: '/projects/$projectId/spaces/$spaceId/$chatId'
      preLoaderRoute: typeof AppProjectsProjectIdSpacesSpaceIdChatIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsGitRoute: typeof AppSettingsGitRoute
  AppSettingsProvidersRoute: typeof AppSettingsProvidersRoute
  AppSettingsSuggestionsRoute: typeof AppSettingsSuggestionsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsGitRoute: AppSettingsGitRoute,
  AppSettingsProvidersRoute: AppSettingsProvidersRoute,
  AppSettingsSuggestionsRoute: AppSettingsSuggestionsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdChatsChatIdRoute: typeof AppProjectsProjectIdChatsChatIdRoute
  AppProjectsProjectIdPlansPlanSlugRoute: typeof AppProjectsProjectIdPlansPlanSlugRoute
  AppProjectsProjectIdChatsIndexRoute: typeof AppProjectsProjectIdChatsIndexRoute
  AppProjectsProjectIdPlansIndexRoute: typeof AppProjectsProjectIdPlansIndexRoute
  AppProjectsProjectIdSettingsIndexRoute: typeof AppProjectsProjectIdSettingsIndexRoute
  AppProjectsProjectIdSkillsIndexRoute: typeof AppProjectsProjectIdSkillsIndexRoute
  AppProjectsProjectIdSpacesIndexRoute: typeof AppProjectsProjectIdSpacesIndexRoute
  AppProjectsProjectIdTasksIndexRoute: typeof AppProjectsProjectIdTasksIndexRoute
  AppProjectsProjectIdSpacesSpaceIdChatIdRoute: typeof AppProjectsProjectIdSpacesSpaceIdChatIdRoute
  AppProjectsProjectIdSpacesSpaceIdIndexRoute: typeof AppProjectsProjectIdSpacesSpaceIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdChatsChatIdRoute: AppProjectsProjectIdChatsChatIdRoute,
  AppProjectsProjectIdPlansPlanSlugRoute:
    AppProjectsProjectIdPlansPlanSlugRoute,
  AppProjectsProjectIdChatsIndexRoute: AppProjectsProjectIdChatsIndexRoute,
  AppProjectsProjectIdPlansIndexRoute: AppProjectsProjectIdPlansIndexRoute,
  AppProjectsProjectIdSettingsIndexRoute:
    AppProjectsProjectIdSettingsIndexRoute,
  AppProjectsProjectIdSkillsIndexRoute: AppProjectsProjectIdSkillsIndexRoute,
  AppProjectsProjectIdSpacesIndexRoute: AppProjectsProjectIdSpacesIndexRoute,
  AppProjectsProjectIdTasksIndexRoute: AppProjectsProjectIdTasksIndexRoute,
  AppProjectsProjectIdSpacesSpaceIdChatIdRoute:
    AppProjectsProjectIdSpacesSpaceIdChatIdRoute,
  AppProjectsProjectIdSpacesSpaceIdIndexRoute:
    AppProjectsProjectIdSpacesSpaceIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppSandboxRoute: typeof AppSandboxRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSandboxRoute: AppSandboxRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
